MAIN_URL = "https://stellarburgers.nomoreparties.site"
REGISTER = "/api/auth/register"
LOGIN = "/api/auth/login"
UPDATE_TOKEN = "/api/auth/token"
GET_USER_DATA = "/api/auth/user"
PATCH_USER_DATA = "/api/auth/user"
CREATE_ORDER = "/api/orders"
GET_INGREDIENTS = "/api/ingredients"