ALREADY_EXISTS_USER_ERROR = "User already exists"
CREATE_USER_WITHOUT_FIELD_ERROR = "Email, password and name are required fields"
INCORRECT_LOGIN = "email or password are incorrect"
CHANGE_USER_DATA_ERROR = "You should be authorised"
INVALID_ORDER_DATA_ERROR = "One or more ids provided are incorrect"